version: '3.5'

services:

    vernemq:
        environment:
            - DOCKER_VERNEMQ_ACCEPT_EULA=yes
            - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
            - MQTT_TOPIC=thndr-trading
        image: erlio/docker-vernemq

    streamer:
        environment:
            - MQTT_HOST=vernemq
            - MQTT_PORT=1883
            - MQTT_TOPIC=thndr-trading
        image: thndr/streamer:0.2
        depends_on:
            - vernemq

    db:
        image: postgres
        restart: always
        # ports:
        #     - "5432:5432"
        environment:
            POSTGRES_PASSWORD: example

    mqtt_client:
        build: mqtt_client
        depends_on:
            - db
            
    api_server:
        build: api_server
        ports:
            - "8000:8000"
        depends_on:
            - db

